Spring:
  datasource:
    url: jdbc:h2:mem:programation-web
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create
        show_sql: true
        format_sql: true
  output:
    ansi:
        enabled: Always
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
